version: '3.8'

services:
  user-service:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:password@db:5432/ecommerce_user_service?schema=public
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=ecommerce_user_service
      - DB_PORT=5432
      - DB_SSL=false
      - JWT_SECRET=local-development-secret
      - PORT=3000
    depends_on:
      - db
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ecommerce_user_service
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: